interaction:
  - name: "collabllm"
    class_name: "recipe.collabllm.collabllm_interation.CollabLLMInteraction"
    config: {
      "user_model": "gpt-4o-mini",
      "num_retries": 3,
      "max_tokens": 512,
      "temperature": 1.0,
      "enable_log": True
    }